### PR TITLE
Update .gitignore

### PR DESCRIPTION
**Pull request by temptemp3**

### CODE REVIEW

**Comment by ameer1234567890** [comment]
Why do we need to gitignore "everything"?

**Comment by temptemp3** [comment]
I think it’s just easier that way. And we don’t have to worry about commiting anything on accident.

**Comment by ameer1234567890** [comment]
This would ignore ALL files, including the script.

**Comment by temptemp3** [comment]
Not if they are already added, which they are.

**Comment by ameer1234567890** [comment]
What about changes? It will stop any changes from being added. There should be better ways than just ignoring the whole repo, IMHO.

**Pull request closed without merging**
